### ISSUE TITLE
docker compose up fail

### ISSUE THREAD

**Issue by Izayda** [ergonode/docker#77]
Hi! Trying to research ergonode on my local machine (Apple M1).

After cloning all reps, run `docker compose up`

```
Building nuxtjs
[+] Building 36.0s (17/17) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                         0.0s
 => => transferring dockerfile: 37B                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                            0.0s
 => => transferring context: 35B                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/node:12.6-alpine                                                                                                          0.7s
 => ERROR importing cache manifest from ergonode/nuxtjs:latest                                                                                                               1.7s
 => ERROR importing cache manifest from ergonode/docsify:latest                                                                                                              1.7s
 => ERROR importing cache manifest from ergonode/nginx:latest                                                                                                                1.8s
 => ERROR importing cache manifest from ergonode/rabbitmq:latest                                                                                                             1.7s
 => ERROR importing cache manifest from ergonode/haproxy:latest                                                                                                              1.7s
 => [node 1/3] FROM docker.io/library/node:12.6-alpine@sha256:182778091c2c27ffa76caa41e762b21a2555118bae00212c52b347bddbc058ba                                               0.0s
 => importing cache manifest from ergonode/php:latest                                                                                                                        0.0s
 => [internal] load build context                                                                                                                                            0.1s
 => => transferring context: 307.74kB                                                                                                                                        0.1s
 => CACHED [node 2/3] COPY config/node/docker-entrypoint.sh /usr/local/bin/docker-entrypoint                                                                                 0.0s
 => CACHED [node 3/3] RUN  set -eux;     chmod +x /usr/local/bin/docker-entrypoint ;     apk add  --no-cache     curl     bash     git                                       0.0s
 => CACHED [nuxtjs 1/4] WORKDIR /srv/app                                                                                                                                     0.0s
 => CACHED [nuxtjs 2/4] WORKDIR /srv/app                                                                                                                                     0.0s
 => CACHED [nuxtjs 3/4] COPY frontend /srv/app/                                                                                                                              0.0s
 => ERROR [nuxtjs 4/4] RUN  set -eux;     npm install ;     npm run modules:all ;     NODE_ENV=production API_BASE_URL=http://localhost:8000/api/v1/ npm run build ;     n  33.3s
------
 > importing cache manifest from ergonode/nuxtjs:latest:
------
------
 > importing cache manifest from ergonode/docsify:latest:
------
------
 > importing cache manifest from ergonode/nginx:latest:
------
------
 > importing cache manifest from ergonode/rabbitmq:latest:
------
------
 > importing cache manifest from ergonode/haproxy:latest:
------
------
 > [nuxtjs 4/4] RUN  set -eux;     npm install ;     npm run modules:all ;     NODE_ENV=production API_BASE_URL=http://localhost:8000/api/v1/ npm run build ;     npm cache clean -f ;     rm -f .env:
#12 0.131 + npm install
#12 31.60
#12 31.60 > deasync@0.1.21 install /srv/app/node_modules/deasync
#12 31.60 > node ./build.js
#12 31.60
#12 31.69 gyp ERR! configure error
#12 31.69 gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
#12 31.69 gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
#12 31.69 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
#12 31.69 gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
#12 31.69 gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
#12 31.69 gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
#12 31.69 gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
#12 31.69 gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
#12 31.69 gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:165:21)
#12 31.69 gyp ERR! System Linux 5.10.25-linuxkit
#12 31.69 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#12 31.69 gyp ERR! cwd /srv/app/node_modules/deasync
#12 31.69 gyp ERR! node -v v12.6.0
#12 31.69 gyp ERR! node-gyp -v v3.8.0
#12 31.69 gyp ERR! not ok
#12 31.69 Build failed
#12 33.16 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
#12 33.16 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#12 33.16 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchify/node_modules/fsevents):
#12 33.16 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#12 33.16 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/cypress-cucumber-preprocessor/node_modules/fsevents):
#12 33.16 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#12 33.16 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/babel-plugin-add-module-exports/node_modules/fsevents):
#12 33.16 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#12 33.16 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
#12 33.16 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#12 33.16
#12 33.16 npm ERR! code ELIFECYCLE
#12 33.16 npm ERR! errno 1
#12 33.16 npm ERR! deasync@0.1.21 install: `node ./build.js`
#12 33.16 npm ERR! Exit status 1
#12 33.16 npm ERR!
#12 33.16 npm ERR! Failed at the deasync@0.1.21 install script.
#12 33.16 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#12 33.20
#12 33.20 npm ERR! A complete log of this run can be found in:
#12 33.20 npm ERR!     /root/.npm/_logs/2021-05-27T07_36_56_196Z-debug.log
------
executor failed running [/bin/sh -c set -eux;     npm install ;     npm run modules:all ;     NODE_ENV=production API_BASE_URL=http://localhost:8000/api/v1/ npm run build ;     npm cache clean -f ;     rm -f .env]: exit code: 1
ERROR: Service 'nuxtjs' failed to build : Build failed
```

How i can fix this?

**Comment by RTodorov** [comment]
I managed to fix this by adding some missing dependencies to the node image.

In the Dockerfile, replace line 198 with this:

```
RUN  set -eux; \
    chmod +x /usr/local/bin/docker-entrypoint ; \
    apk add  --no-cache \
    curl \
    bash \
    git \
    python \
    make \
    g++ \
    gcc
```
